### ISSUE TITLE
Too many errors 

### ISSUE THREAD

**Issue by kN6jq** [0xPugazh/SubDomz#14]
please fix it 
![image](https://user-images.githubusercontent.com/27048404/200174275-dd7d6957-0f04-4ade-8845-76123a8480b7.png)

![image](https://user-images.githubusercontent.com/27048404/200174234-445cbbc7-4f06-46e9-bd49-907345822e66.png)

**Comment by sasholy** [comment]
Help me too, thx.

flag provided but not defined: -threads
Usage of gau:
  -b string
        extensions to skip, ex: ttf,woff,svg,png,jpg
  -json
        write output as json
  -o string
        filename to write results to
  -p string
        HTTP proxy to use
  -providers string
        providers to fetch urls for (default "wayback,otx,commoncrawl")
  -retries uint
        amount of retries for http client (default 5)
  -subs
        include subdomains of target domain
  -t uint
        number of threads to use (default 1)
  -v    enable verbose mode
  -version
        show gau version
Usage of github-subdomains:
  -d string
        domain you are looking for (required)
  -e    extended mode, also look for <dummy>example.com
  -k    exit the program when all tokens have been disabled
  -o string
        output file, default: <domain>.txt
  -q    quick mode, avoid extra searches with languages and noise added
  -raw
        raw output
  -t string
        github token (required), can be:
          • a single token
          • a list of tokens separated by comma
          • a file containing 1 token per line
        if the options is not provided, the environment variable GITHUB_TOKEN is readed, it can be:
          • a single token
          • a list of tokens separated by comma
./SubDomz: line 196: sublist3r.py: command not found
parse error: Invalid numeric literal at line 1, column 7

**Comment by 0xPugazh** [comment]
Hi @sasholy Your Gau tool is outdated. So, it shows the error. 
And provide the API keys in Environment Variables in SubDomz file L45.

**Comment by 0xPugazh** [comment]
Hi @kN6jq Please, configure the go path (i.e. with $GOPATH/bin in your $PATH) and the Crobat error is not from Subdomz. check https://github.com/Cgboal/SonarSearch/issues

**Comment by sasholy** [comment]
> Hi @sasholy Your Gau tool is outdated. So, it shows the error. And provide the API keys in Environment Variables in SubDomz file L45.

──(kali㉿kali)-[~/SubDomz]
└─$ ./SubDomz -d palantir.com > ok.txt
./SubDomz: line 196: sublist3r.py: command not found
parse error: Invalid numeric literal at line 1, column 7
                                                                             
┌──(kali㉿kali)-[~/SubDomz]
└─$ 
mistake, thx
