### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Ericcmn** [0xPugazh/SubDomz#16]
Hi, thanks to your team for this nice project.
After working with this project for a while, my team noticed some bugs that if fixed would make this app work better. We will examine some of these problems below.
1. GAU does not work and shows help.
2. After entering GitHub tokens doesn't recognize it.
3. Some programs no longer work.
4. For cases where the user does not want to use their tokens, there is no option to skip.
thank you.
Bendell

**Comment by 0xPugazh** [comment]
1. fixed the gau error and github subdomains error
2. remove the no longer worked sources and tools

+ For cases where the user does not want to use their tokens, there is no option to skip. - will add this in future
